apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: axhcl29bu-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: axhcl29bu-python 
  name: axhcl29bu-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: axhcl29bu-python 
